export const events = [
  {
    id: 1,
    name: "Rocktaves",
    category: "Music",
    day: 1,
    time: "22:00",
    venue: "Auditorium",
    registrations: 1125,
  },
  {
    id: 2,
    name: "Code Relay",
    category: "Tech",
    day: 2,
    time: "10:00",
    venue: "NAB Audi",
    registrations: 278,
  },
  {
    id: 3,
    name: "Robowars",
    category: "Tech",
    day: 0,
    time: "21:00",
    venue: "Rotunda",
    registrations: 820,
  },
  {
    id: 4,
    name: "Battle of Bands",
    category: "Music",
    day: 0,
    time: "19:00",
    venue: "Open Air Theatre",
    registrations: 640,
  },
  {
    id: 5,
    name: "Hackathon 24H",
    category: "Tech",
    day: 1,
    time: "09:00",
    venue: "Innovation Lab",
    registrations: 512,
  },
  {
    id: 6,
    name: "Startup Pitch",
    category: "Tech",
    day: 2,
    time: "14:00",
    venue: "NAB Audi",
    registrations: 305,
  },
  {
    id: 7,
    name: "Street Dance Showdown",
    category: "Cultural",
    day: 1,
    time: "18:00",
    venue: "Rotunda",
    registrations: 890,
  },
  {
    id: 8,
    name: "Dramatics Night",
    category: "Cultural",
    day: 2,
    time: "20:00",
    venue: "Auditorium",
    registrations: 470,
  },
  {
    id: 9,
    name: "Fashion Parade",
    category: "Cultural",
    day: 0,
    time: "17:00",
    venue: "Open Air Theatre",
    registrations: 730,
  },
  {
    id: 10,
    name: "Cricket Finals",
    category: "Sports",
    day: 2,
    time: "16:00",
    venue: "Main Ground",
    registrations: 980,
  },
  {
    id: 11,
    name: "Football Knockout",
    category: "Sports",
    day: 1,
    time: "15:00",
    venue: "Sports Complex",
    registrations: 860,
  },
  {
    id: 12,
    name: "Basketball 3v3",
    category: "Sports",
    day: 0,
    time: "13:00",
    venue: "Indoor Stadium",
    registrations: 410,
  },
  {
    id: 13,
    name: "Open Mic Night",
    category: "Music",
    day: 2,
    time: "21:30",
    venue: "Student Activity Center",
    registrations: 350,
  },
  {
    id: 14,
    name: "AI Workshop",
    category: "Tech",
    day: 0,
    time: "11:00",
    venue: "Computer Lab 1",
    registrations: 260,
  },
  {
    id: 15,
    name: "Photography Walk",
    category: "Cultural",
    day: 1,
    time: "07:00",
    venue: "Campus Gate",
    registrations: 190,
  },
  {
    id: 16,
    name: "Table Tennis Tournament",
    category: "Sports",
    day: 2,
    time: "12:00",
    venue: "Indoor Stadium",
    registrations: 300,
  },
  {
    id: 17,
    name: "Classical Music Evening",
    category: "Music",
    day: 1,
    time: "20:00",
    venue: "Auditorium",
    registrations: 410,
  },
];
